// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkgixaimezdrluvownn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a2dpeGFpbWV6ZHJsdXZvd25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzEwNDUsImV4cCI6MjA2MzcwNzA0NX0.y7cSIVVHUkOW8fQvDAlAPzFQko5KbErb5gROCxw50xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);